### PR TITLE
V1.0.5

### PR DESCRIPTION
**Pull request by nicx92**
* Fix Broken Whatsapp Button Link
* Added Phone Number On homepage
* Added twitter profile button on navbar
* fixed map's size on homepage

### CODE REVIEW

**Review by narangopticals — APPROVED** [review]
Tested, Deploying

**Review by nicx92 — COMMENTED** [review]
👍

**Review by nik3792 — COMMENTED** [review]
Shaded look added

**Review by narangopticals — APPROVED** [review]
👍

**Review by nicx92 — COMMENTED** [review]
👍

**Pull request closed without merging**
